application:
  title: GameList
  version: 1.0.0

server:
  port: 8989
  shutdown: graceful

spring:
  mvc:
    problemdetails:
      enabled: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: game-service
          uri: ${GAME_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/game-service/**
          filters:
            - SemiAuthenticationFilter
            - RewritePath=/game-service/?(?<segment>.*), /${segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/?(?<segment>.*), /${segment}
        - id: social-service
          uri: ${SOCIAL_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/social-service/**
          filters:
            - SemiAuthenticationFilter
            - RewritePath=/social-service/?(?<segment>.*), /${segment}
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/user-service/**
          filters:
            - AuthenticationFilter
            - RewritePath=/user-service/?(?<segment>.*), /${segment}
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: game-service
        url: /v3/api-docs/game-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: social-service
        url: /v3/api-docs/social-service
      - name: auth-service
        url: /v3/api-docs/auth-service
