application:
  version: 1.0.0

server:
  port: 8081
  shutdown: graceful

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5332/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

resilience4j:
  retry:
    backends:
      game-service:
        max-attempts: 2
        wait-duration: 1s
  circuitbreaker:
    backends:
      game-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50

swagger:
  api-gateway-url: http://localhost:8989/social-service
social:
  game-service-url: ${GAME_SERVICE_URL:http://localhost:8080}
  go-service-url: ${GO_SERVICE_URL:http://localhost:9000}
  user-service-url: ${USER_SERVICE_URL:http://localhost:8989/user-service}

grpc:
  server:
    port: ${GRPC_PORT:6566}
  client:
    auth-service-go:
      address: static://${AUTH_SERVICE_ADDRESS:localhost:6567}
      negotiation-type: plaintext
    user-service-dotnet:
      address: static://${USER_SERVICE_ADDRESS:localhost:6568}
      negotiation-type: plaintext
